### ISSUE TITLE
render charts inside <clipPath>

### ISSUE THREAD

**Issue by douglaskariuki** [reaviz/reaviz#77] opened 2022-06-11 19:58 UTC
render charts inside a clipPath to prevent elements from overflowing the bounding box

**Comment by amcdnl** [comment] 2022-06-13 11:36
This is by design. Its needed for the zooming/pan/scrub. What problem is it causing for you?

**Comment by amcdnl** [comment] 2022-06-13 22:42
Gotcha. Thats kinda like how the zoom works. I'm going to close this since its not an issue.

**Closed by amcdnl** 2022-06-13 22:42 UTC
